// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();
const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createDisabledAuth = () => {
  const warn = () => {
    console.warn(
      "Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable auth."
    );
  };

  return {
    onAuthStateChange: (callback: (event: string, session: null) => void) => {
      warn();
      callback("SIGNED_OUT", null);
      return { data: { subscription: { unsubscribe: () => {} } } };
    },
    getSession: async () => {
      warn();
      return { data: { session: null }, error: null };
    },
    signInWithPassword: async () => {
      warn();
      return { data: { session: null, user: null }, error: { message: "Supabase is not configured." } };
    },
    signUp: async () => {
      warn();
      return { data: { session: null, user: null }, error: { message: "Supabase is not configured." } };
    },
    signOut: async () => {
      warn();
      return { error: null };
    },
  };
};

export const supabase = hasSupabaseConfig
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : ({ auth: createDisabledAuth() } as unknown as ReturnType<typeof createClient<Database>>);